export default {
  primayColor: '#007AFF',
  primaryLight: '#1a87ff',
  primaryDark: '#006ee6',
  accentColor: '#27ae60',
  apiUrl: 'https://tasks.infynno.com/api',
  logo: '../../logo.png',
  appName: 'Infynno HRMS',
  successColor: '#27ae60',
  errorColor: '#c0392b',
  warningColor: '#e67e22',
  textColor: '#7f8c8d',
  textDark: '#2c3e50',
  pendingColor: '#303030',
  backgroundColor: '#EBEEF7',
}
