export default {
  msgEnterValidName: 'Please enter full name',
  msgEnterValidUserName: 'Please enter user name',
  msgImageValidation: 'Please select image',
  msgEnterEmail: 'Please enter email address',
  msgEnterUsername: 'Please enter username',
  msgEnterPassword: 'Please enter password',
  msgEnterValidEmail: 'Please enter a valid email address',
  msgEnterValidPassword: 'Please enter valid password',
  msgEnterConfirmPassword: 'Please enter confirm password',
  msgPasswordLength: 'Password length must be 8 characters',
  msgConfirmRequired: 'Please enter your password again to confirm it',
  msgPassMatch: 'Password and confirm password must match',
  msgEnterOTP: 'Please enter OTP',
  msgEnterValidOTP: 'OTP length must be 6 character',
  commentDelete: 'Are you sure to delete this comment?',
  deletePost: 'Are you sure to delete this post?',
  msgBlockUserConfirm: 'Are you sure to block this user?',
  submitText: 'Submit',
  btn: {
    continue: 'Continue',
    resendCode: 'Resend Code',
  },
  title: {
    verification: 'Enter Verification',
    appTitle: 'Boiler Plat',
  },
  description: {
    verificationDesc: 'Enter the 6-digit verification code we sent to ',
    emailDescription: 'Your high school email address',
    dontHaveOne: "Don't have one?",
    eightCharacter: '• 8 Characters',
    specialSymbol: '• Special symbol',
    oneNumber: '• 1 Number',
    dotWithSpace: '  ·  ',
  },
  formTitle: {
    emailAddress: 'Email Address',
    fullName: 'Full Name',
    password: 'Password',
    userName: 'User Name',
    changePassword: 'Change Password',
    confirmPassword: 'Confirm Password',
  },
  alertMessage: {
    msgSignOut: 'Are you sure you want to signout?',
    leaveGroup: 'Are you sure want to leave this group?',
  },
  cancelText: 'Cancel',
};
